version: "3.8"

services:
  fastapi-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=local
      - DATABASE_URL=mongodb://mongo:27017/biwoco_test  # Kết nối tới MongoDB
      - REDIS_URL=redis://redis:6379  # Kết nối tới Redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6380:6379"

